services:
  app:
    image: fleet-telemetry-integration-tests:latest
    volumes:
      - ./test/integration/config.json:/etc/tesla/config.json:ro
      - ./test/integration/test-certs:/etc/tesla/certs/server:ro
      - /tmp/fleet-telemetry/:/tmp/fleet-telemetry:rw
    command:
      - "/go/bin/fleet-telemetry"
      - "-config=/etc/tesla/config.json"
    ports:
      - "4443:4443"
      - "4269:4269"
      - "8080:8080"
      - "9090:9090"
    environment:
      SUPPRESS_TLS_HANDSHAKE_ERROR_LOGGING: true
    depends_on:
      errbit:
        condition: service_healthy

  # Errbit implements airbrake's API, so we can use it to test the airbrake
  errbit:
    image: errbit/errbit:v0.8.0
    platform: linux/amd64
    ports:
      - '48088:8080'
    command: sh -c "bundle exec rake errbit:bootstrap && bundle exec puma -C config/puma.default.rb"
    volumes:
      - ./test/integration/errbit/apps.json:/initialize/apps.json:ro
      - ./test/integration/errbit/site_configs.json:/initialize/site_configs.json:ro
      - ./test/integration/errbit/users.json:/initialize/users.json:ro
      - ./test/integration/errbit/init_errbit.rake:/app/lib/tasks/init_errbit.rake:ro
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      RACK_ENV: production
      PORT: 8080
      MONGO_URL: mongodb://errbit_user:errbit_password@mongodb:27017/errbit
      # Add these environment variables to control the initialization
      ERRBIT_ADMIN_EMAIL: admin@example.com
      ERRBIT_ADMIN_PASSWORD: password
      ERRBIT_ADMIN_USER: admin

  mongodb:
    image: mongo:4.1
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: errbit-admin
      MONGO_INITDB_ROOT_PASSWORD: 42
    healthcheck:
      test: mongo -u errbit-admin  -p 42  --eval "db.adminCommand('ping')" --quiet
      interval: 5s
    volumes:
      - ./test/integration/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  prometheus:
    image: prom/prometheus
    ports:
      - "19090:9090"
    volumes:
      - ./test/integration/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - "13000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./test/integration/grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      prometheus:
        condition: service_started
